// This file is generated by the build process
// Placeholder to satisfy Vercel's function detection
module.exports = async (req, res) => {
  res.status(500).json({ message: "Function not built yet" });
};

