// This file is generated by script/build-api.ts
// It will be overwritten during the build process
// This placeholder ensures Vercel can detect the serverless function

export default async function handler(req, res) {
  res.status(500).json({ 
    error: "Build not completed",
    message: "This file should be replaced by the build script" 
  });
}
